name: CI pipeline

on: [push]

jobs:
  docker-build:
    if: "!contains(github.event.head_commit.message, 'GHA autoupdate')"
    runs-on: [ubuntu-22.04]
    strategy:
      fail-fast: true
    steps:
      - name: Login to the docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set docker tag and backend version variable
        id: version
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo ::set-output name=tag::${GITHUB_SHA::6}
          else
            echo ::set-output name=tag::${{ github.ref_name }}
          fi

      - name: Build docker image
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
            pwd
            ls -la ./
            docker build -t jpazdyga/whoami:${VERSION} -f Dockerfile .
        #- name: Run Snyk to check Docker image for vulnerabilities
        #id: snyk
        #env:
        #  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        #  VERSION: ${{ steps.version.outputs.tag }}
        #run: |
        #  snyk container test --severity-threshold=high --fail-on=upgradable jpazdyga/whoami:${VERSION}
      - name: Push docker image
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
          docker push jpazdyga/whoami:${VERSION}
        #if: steps.snyk.outcome == 'success'

      - name: Update values.yaml file
        id: sed
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
          cat helm/values.yaml
          sed -i "s|^  tag:.*|  tag: ${VERSION}|g" helm/values.yaml
          cat helm/values.yaml

      - name: Push updated values.yaml file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_ATLANTIS_PAT }}
        with:
          source_file: 'helm/values.yaml'
          destination_repo: 'jpazdyga/whoami'
          destination_folder: 'helm'
          user_email: 'gha@lascalia.com'
          user_name: 'Github Actions'
          commit_message: 'GHA autoupdate of values.yaml to be consumed by argocd'
