name: CI pipeline

on: [push]

jobs:
  docker-build:
    needs: build
    strategy:
      fail-fast: true
    steps:
      - name: Set docker tag and backend version variable
        id: version
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo ::set-output name=tag::${GITHUB_SHA::6}
          else
            echo ::set-output name=tag::${{ github.ref_name }}
          fi

      - name: Build docker image
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
            docker build -t jpazdyga/whoami:${VERSION} -f Dockerfile .
      - name: Run Snyk to check Docker image for vulnerabilities
        id: snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
          snyk container test --severity-threshold=high --fail-on=upgradable jpazdyga/whoami:${VERSION}
      - name: Push docker image
        env:
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
          docker push jpazdyga/whoami:${VERSION}
        if: steps.snyk.outcome == 'success'
